### PR TITLE
Adapt typos in JSON

### PR DESCRIPTION
**Pull request by b123400**
#162 

There are so many spellings in the JSON....
"Zulassungsnummer"
"Zulassungsnummern"
"Zulasssungsnumer"
"Zulaswsungsnummer"
"No d'autorisation"
"No d’autorisation"
"No d’autorisation :"
"Nos d’autorisation"
"Nos. d'autorisation"
"Nos. d’autorisation"

### CODE REVIEW

**Comment by zdavatz** [comment]
Can we somehow work around the spellings? Like for the registration number? It should always have 5 digits.

**Comment by b123400** [comment]
I have added the typos to cpp2sqlite, so it should be ok now, unless more typos are added. I can try to extract anything with 5 digits, but it may not be very accurate, sometimes an entry has `"Zulassungsnummer" : "63094 und 63095"`, which means I have to split the string.

https://www.swissmedic.ch/swissmedic/de/home/humanarzneimittel/marktueberwachung/qualitaetsmaengel-und-chargenrueckrufe/chargenrueckrufe/recall-Valsartan-Helvepharm-Valsartan-HCT-Helvepharm.html

**Comment by zdavatz** [comment]
Ok, great. We are doing this with Ruby as well: https://github.com/zdavatz/oddb.org/search?q=update_recall_feed

**Comment by zdavatz** [comment]
Now getting 65 Batch recalls. Looking good!

**Comment by zdavatz** [comment]
The Answer from Swissmedic:

Bildschirmfoto 2021-01-21 um 11 15 42

**Pull request merged**
